items_pretx_sub2 <- c(
  # "cdrs01s","cdrs02s",
  # "cdrs03s","cdrs04s",
  # "cdrs05s","cdrs06s",
  # "cdrs07s","cdrs08s",
  # "cdrs09s","cdrs10s",
  # "cdrs11s","cdrs12s",
  # "cdrs13s","cdrs14s",
  # "cdrs15","cdrs16","cdrs17",
  
  "rrs_01","rrs_02","rrs_03","rrs_04","rrs_05","rrs_06","rrs_07",
  "rrs_08","rrs_09","rrs_10","rrs_11","rrs_12","rrs_13","rrs_14",
  "rrs_15","rrs_16","rrs_17","rrs_18","rrs_19","rrs_20","rrs_21","rrs_22",
  
  # "upps_01_doingsomething","upps_02_thrillingthings",
  # "upps_03_seethings","upps_04_blurtout","upps_05_upsetunfinished",
  # "upps_06_stopandthink","upps_07_feelbad","upps_08_waterskiing",
  # "upps_09_hatetostop","upps_10_whattodo","upps_11_feelbad",
  # "upps_12_takingrisks","upps_13_thinkhard","upps_14_parachutejumping",
  # "upps_15_finish","upps_16_carefulapproach","upps_17_actwithoutthinking",
  # "upps_18_thrillingthings","upps_19_getthingsdone","upps_20_rejected",
  # "upps_21_fly","upps_22_getsthejobdone","upps_23_careful",
  # "upps_24_finish","upps_25_knowwhattoexpect","upps_26_actwithoutthinking",
  # "upps_27_ski","upps_28_stopandthink","upps_29_choices","upps_30_mad",
  # "upps_31_drivingfast","upps_32_crazythings","upps_33_veryhappy",
  # "upps_34_thrilled","upps_35_greatmood","upps_36_actwithoutthinking",
  # "upps_37_troublehappy","upps_38_outofcontrol","upps_39_losecontrol",
  # "upps_40_problemsinlife",
  
  # "scared_01_hardtobreathe","scared_02_headaches_school",
  # "scared_03_dontlikeunknownppl","scared_04_scarednotsleepathome",
  # "scared_05_worrypeoplelikeme","scared_06_passingoutfrightened",
  # "scared_07_nervous","scared_08_follow_parents","scared_09_looknervous",
  # "scared_10_nervouswithppldontknow","scared_11_stomachachesschool",
  # "scared_12_frightened","scared_13_worrysleepalone",
  # "scared_14_worrybeinggood","scared_15_thingsunrealscared",
  # "scared_16_nightmaresparents","scared_17_worrygoingschool",
  # "scared_18_heartbeatsfastscared","scared_19_getshaky",
  # "scared_20_nightmaresbadtome","scared_21_worrythingsworkme",
  # "scared_22_sweatwhenscared","scared_23_worrier",
  # "scared_24_frightenednoreason","scared_25_afraidalonehouse",
  # "scared_26_hardtalktoppl","scared_27_chokingwhenscared",
  # "scared_28_peoplesayiworry","scared_29_dontlikeawayfamily",
  # "scared_30_afraidpanicattacks","scared_31_worryhappenstoparents",
  # "scared_32_shy","scared_33_worryfuture","scared_34_throwingupscared",
  # "scared_35_worryhowdothings","scared_36_scaredgotoschool",
  # "scared_37_worrypast","scared_38_dizzywhenscared",
  # "scared_39_nervouswithothers","scared_40_nervouspartiesdances",
  # "scared_41_shy",
  
  "trash_01_automatically","trash_02_same_places","trash_03_hard_not_to",
  "trash_04_sad_anx_annoyed","trash_05_unintentionally",
  "trash_06_when_alone","trash_07_effort_to_stop","trash_08_same_times_day",
  "trash_09_start_before_realize","trash_10_response_same_sit",
  
  "pswq_01_worries_bother_me","pswq_02_dont_worry_things",
  "pswq_03_things_worry_me","pswq_04_cant_help_worry",
  "pswq_05_worry_under_pressure","pswq_06_always_worrying",
  "pswq_07_easy_stop_worrying","pswq_08_worry","pswq_09_never_worry",
  "pswq_10_worry_all_my_life","pswq_11_notice_i_worry",
  "pswq_12_start_worry_cant_stop","pswq_13_worry_all_time",
  "pswq_14_worry_till_thngs_done",
  
  "sari_01_angry","sari_02_angry","sari_03_angry","sari_04_angry",
  "sari_05_angry",
  #"sari_06_angry",
  "sari_07_angry","sari_08_angry",
  "sari_09_angry","sari_10_angry","sari_11_angry","sari_01_sad",
  "sari_02_sad","sari_03_sad","sari_04_sad","sari_05_sad",
  #"sari_06_sad",
  "sari_07_sad","sari_08_sad","sari_09_sad",
  "sari_10_sad",
  #"sari_11_sad",
  
  "rum_vas_01_frequency",
  "rum_vas_02_control",
  "rum_vas_03_duration",
  "rum_vas_04_distress"
  
  )
  
  # "meaq_01_free_pain","meaq_02_not_feel_bad",
  # "meaq_03_pain_suffering","meaq_04_never_feel_pain",
  # "meaq_05_rid_neg_emotions","meaq_06_anything_feel_btr",
  # "meaq_07_remove_pain_mem","meaq_08_no_upset_feelings",
  # "meaq_09_no_unple_mems","meaq_10_not_think_upset",
  # "meaq_11_avoid_neg_thoughts","meaq_12_think_smthng_else",
  # "meaq_13_hard_know_feeling","meaq_14_disconnect_emo",
  # "meaq_15_diff_how_feeling","meaq_16_turn_off_emotions",
  # "meaq_17_numb_feelings","meaq_18_shut_off_feelings","meaqa_quiet",
  # "meaqa_smother_feelings","meaqa_hide_annoyance","meaqa_bottle_anger",
  # "meaqa_say_what_feel","meaqa_refuse_argue","meaqa_avoid_scene",
  # "meaqs_bottle_it_up","meaqs_let_others_see_feel","meaqs_keep_quiet",
  # "meaqs_hide_unhappy","meaqs_smother_feelings","meaqs_refuse_say_anything",
  # "meaq_put_on_happy_face","meaqw_tell_others","meaqw_others_see_how_feel",
  # "meaqw_refuse_say_anything","meaqw_say_what_feel","meaqw_bottle_it_up",
  # "meaqw_keep_quiet","meaqw_smother_feelings",

  # "mwds_01d_wanderingthoughts",
  # "mwds_02d_enjoymindwandering","mwds_03d_boredom",
  # "mwds_04d_absorbedinfantasy","mwds_01s_wanderingthoughts",
  # "mwds_02s_pulledfromtopic","mwds_03s_nocontrol",
  # "mwds_04s_mindwandering",

  # "bisbas_02_rarely_fear_nervous",
  # "bisbas_08_critique_hurts",
  # "bisbas_13_worry_upset_some1_mad",
  # "bisbas_16_work_up_unpleasant",
  # "bisbas_19_worry_do_poorly",
  # "bisbas_22_few_fears",
  # "bisbas_24_worry_mistakes"

